DEFAULT_FIELDS = [
    {
        "feld_id": 1,
        "name": "Los",
        "typ": "Los",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Dunkelgrau",
        "zusatz_regel": "Alle starten gemeinsam. Wer hier landet, bekommt neuen Schwung für die nächste Runde.",
        "besitzer": None,
    },
    {
        "feld_id": 2,
        "name": "Lächelallee",
        "typ": "Straße",
        "kaufpreis": "2 Punkte",
        "miete": "1 Punkt",
        "farbe": "Braun",
        "zusatz_regel": "Ein schneller Icebreaker bringt alle sofort ins Spiel.",
        "besitzer": None,
    },
    {
        "feld_id": 3,
        "name": "Konfettiplatz",
        "typ": "Straße",
        "kaufpreis": "3 Punkte",
        "miete": "2 Punkte",
        "farbe": "Braun",
        "zusatz_regel": "Feiere deinen Zug mit einer spontanen Miniaufgabe oder einer kleinen Jubelrunde.",
        "besitzer": None,
    },
    {
        "feld_id": 4,
        "name": "Gemeinschaftspark",
        "typ": "Gemeinschaft",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Braun",
        "zusatz_regel": "Alle denken sich zusammen eine kurze freundliche Gemeinschaftsaktion aus.",
        "besitzer": None,
    },
    {
        "feld_id": 5,
        "name": "Sonnenpromenade",
        "typ": "Straße",
        "kaufpreis": "5 Punkte",
        "miete": "3 Punkte",
        "farbe": "Braun",
        "zusatz_regel": "Ein strahlendes Feld mit starkem Auftakt für aktive Spielerinnen und Spieler.",
        "besitzer": None,
    },
    {
        "feld_id": 6,
        "name": "Glücksgasse",
        "typ": "Straße",
        "kaufpreis": "4 Punkte",
        "miete": "2 Punkte",
        "farbe": "Hellblau",
        "zusatz_regel": "Wer hier landet, erzählt kurz seinen bisher besten Spielzug.",
        "besitzer": None,
    },
    {
        "feld_id": 7,
        "name": "Bühnenviertel",
        "typ": "Straße",
        "kaufpreis": "5 Punkte",
        "miete": "3 Punkte",
        "farbe": "Hellblau",
        "zusatz_regel": "Eine kleine Geste oder Pose bringt Extra-Atmosphäre an den Tisch.",
        "besitzer": None,
    },
    {
        "feld_id": 8,
        "name": "Musikmarkt",
        "typ": "Straße",
        "kaufpreis": "6 Punkte",
        "miete": "4 Punkte",
        "farbe": "Hellblau",
        "zusatz_regel": "Summt kurz einen Song, den alle kennen könnten.",
        "besitzer": None,
    },
    {
        "feld_id": 9,
        "name": "Festivalforum",
        "typ": "Straße",
        "kaufpreis": "7 Punkte",
        "miete": "5 Punkte",
        "farbe": "Hellblau",
        "zusatz_regel": "Hier darf laut gejubelt werden: ein echtes Highlight im frühen Spiel.",
        "besitzer": None,
    },
    {
        "feld_id": 10,
        "name": "Ideenjoker",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "zusatz_regel": "Wähle für deinen nächsten Zug eine beliebige freundliche Kreativaktion.",
        "besitzer": None,
    },
    {
        "feld_id": 11,
        "name": "Kreativkai",
        "typ": "Straße",
        "kaufpreis": "6 Punkte",
        "miete": "4 Punkte",
        "farbe": "Pink",
        "zusatz_regel": "Nenne etwas, das heute für gute Laune gesorgt hat.",
        "besitzer": None,
    },
    {
        "feld_id": 12,
        "name": "Designpassage",
        "typ": "Straße",
        "kaufpreis": "7 Punkte",
        "miete": "5 Punkte",
        "farbe": "Pink",
        "zusatz_regel": "Ein Feld mit klarer Linie und starkem Auftritt.",
        "besitzer": None,
    },
    {
        "feld_id": 13,
        "name": "Studiozeile",
        "typ": "Straße",
        "kaufpreis": "8 Punkte",
        "miete": "6 Punkte",
        "farbe": "Pink",
        "zusatz_regel": "Erfinde in einem Satz einen Titel für eure heutige Runde.",
        "besitzer": None,
    },
    {
        "feld_id": 14,
        "name": "Lichtbogen",
        "typ": "Straße",
        "kaufpreis": "9 Punkte",
        "miete": "7 Punkte",
        "farbe": "Pink",
        "zusatz_regel": "Ein besonders sichtbares Feld für starke Zwischensprints.",
        "besitzer": None,
    },
    {
        "feld_id": 15,
        "name": "Glanzgalerie",
        "typ": "Straße",
        "kaufpreis": "10 Punkte",
        "miete": "8 Punkte",
        "farbe": "Pink",
        "zusatz_regel": "Teile kurz deinen Lieblingsmoment der Partie.",
        "besitzer": None,
    },
    {
        "feld_id": 16,
        "name": "Abenteuerring",
        "typ": "Straße",
        "kaufpreis": "6 Punkte",
        "miete": "4 Punkte",
        "farbe": "Orange",
        "zusatz_regel": "Behalte den Schwung: dieses Feld steht für mutige Züge.",
        "besitzer": None,
    },
    {
        "feld_id": 17,
        "name": "Entdeckerweg",
        "typ": "Straße",
        "kaufpreis": "7 Punkte",
        "miete": "5 Punkte",
        "farbe": "Orange",
        "zusatz_regel": "Nenne einen Ort, den du gerne einmal besuchen würdest.",
        "besitzer": None,
    },
    {
        "feld_id": 18,
        "name": "Teamspielplatz",
        "typ": "Straße",
        "kaufpreis": "8 Punkte",
        "miete": "6 Punkte",
        "farbe": "Orange",
        "zusatz_regel": "Kurze Mini-Challenge zu zweit oder in der Gruppe.",
        "besitzer": None,
    },
    {
        "feld_id": 19,
        "name": "Rätselresidenz",
        "typ": "Straße",
        "kaufpreis": "9 Punkte",
        "miete": "7 Punkte",
        "farbe": "Orange",
        "zusatz_regel": "Stelle den anderen eine leichte Schätz- oder Ratefrage.",
        "besitzer": None,
    },
    {
        "feld_id": 20,
        "name": "Ruheoase",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "zusatz_regel": "Hier darf kurz entspannt werden. Perfekt für einen ruhigen Moment zwischen zwei Highlights.",
        "besitzer": None,
    },
    {
        "feld_id": 21,
        "name": "Panoramaweg",
        "typ": "Straße",
        "kaufpreis": "8 Punkte",
        "miete": "6 Punkte",
        "farbe": "Rot",
        "zusatz_regel": "Ein starkes Mittelfeld mit klarer Präsenz.",
        "besitzer": None,
    },
    {
        "feld_id": 22,
        "name": "Sternenplatz",
        "typ": "Straße",
        "kaufpreis": "9 Punkte",
        "miete": "7 Punkte",
        "farbe": "Rot",
        "zusatz_regel": "Nenne eine Stärke der Person links von dir.",
        "besitzer": None,
    },
    {
        "feld_id": 23,
        "name": "Pausebank",
        "typ": "Gefängnis",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rot",
        "zusatz_regel": "Keine Strafe, nur ein ruhiger Zwischenhalt mit Gelegenheit zum Neustart.",
        "besitzer": None,
    },
    {
        "feld_id": 24,
        "name": "Lichterhof",
        "typ": "Straße",
        "kaufpreis": "10 Punkte",
        "miete": "8 Punkte",
        "farbe": "Rot",
        "zusatz_regel": "Ein Premium-Feld für elegante Spielzüge.",
        "besitzer": None,
    },
    {
        "feld_id": 25,
        "name": "Freundschaftsforum",
        "typ": "Straße",
        "kaufpreis": "11 Punkte",
        "miete": "9 Punkte",
        "farbe": "Rot",
        "zusatz_regel": "Sage einer Person am Tisch etwas Aufmunterndes oder Nettes.",
        "besitzer": None,
    },
    {
        "feld_id": 26,
        "name": "Genussgarten",
        "typ": "Straße",
        "kaufpreis": "9 Punkte",
        "miete": "7 Punkte",
        "farbe": "Gelb",
        "zusatz_regel": "Das Spieltempo bleibt hoch, die Stimmung entspannt.",
        "besitzer": None,
    },
    {
        "feld_id": 27,
        "name": "Lachterrasse",
        "typ": "Straße",
        "kaufpreis": "10 Punkte",
        "miete": "8 Punkte",
        "farbe": "Gelb",
        "zusatz_regel": "Teile eine harmlose, lustige Beobachtung aus der Runde.",
        "besitzer": None,
    },
    {
        "feld_id": 28,
        "name": "Ideenwerk",
        "typ": "Werk",
        "kaufpreis": "12 Punkte",
        "miete": "9 Punkte",
        "farbe": "Gelb",
        "zusatz_regel": "Dieses Feld steht für clevere Einfälle und kreative Vorteile.",
        "besitzer": None,
    },
    {
        "feld_id": 29,
        "name": "Jubelallee",
        "typ": "Straße",
        "kaufpreis": "11 Punkte",
        "miete": "9 Punkte",
        "farbe": "Gelb",
        "zusatz_regel": "Hier fühlt sich jeder erfolgreiche Zug direkt größer an.",
        "besitzer": None,
    },
    {
        "feld_id": 30,
        "name": "Fairplay-Zentrale",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "zusatz_regel": "Eine gute Gelegenheit, die Runde freundlich und ausgeglichen zu halten.",
        "besitzer": None,
    },
    {
        "feld_id": 31,
        "name": "Sommerbühne",
        "typ": "Straße",
        "kaufpreis": "10 Punkte",
        "miete": "8 Punkte",
        "farbe": "Grün",
        "zusatz_regel": "Ein spätes Highlight mit großem Auftritt.",
        "besitzer": None,
    },
    {
        "feld_id": 32,
        "name": "Abenteuerpier",
        "typ": "Straße",
        "kaufpreis": "11 Punkte",
        "miete": "9 Punkte",
        "farbe": "Grün",
        "zusatz_regel": "Nenne eine Sache, die du dieses Jahr noch ausprobieren möchtest.",
        "besitzer": None,
    },
    {
        "feld_id": 33,
        "name": "Kreativcampus",
        "typ": "Straße",
        "kaufpreis": "12 Punkte",
        "miete": "10 Punkte",
        "farbe": "Grün",
        "zusatz_regel": "Hier entstehen neue Impulse für den Endspurt.",
        "besitzer": None,
    },
    {
        "feld_id": 34,
        "name": "Eventhafen",
        "typ": "Straße",
        "kaufpreis": "13 Punkte",
        "miete": "11 Punkte",
        "farbe": "Grün",
        "zusatz_regel": "Ein starkes Feld kurz vor dem Zielbereich.",
        "besitzer": None,
    },
    {
        "feld_id": 35,
        "name": "Fantasiepark",
        "typ": "Straße",
        "kaufpreis": "14 Punkte",
        "miete": "12 Punkte",
        "farbe": "Grün",
        "zusatz_regel": "Das Finale wird kreativ: denk dir einen kurzen Teamtitel für eure Runde aus.",
        "besitzer": None,
    },
    {
        "feld_id": 36,
        "name": "Erlebnisbahnhof",
        "typ": "Bahnhof",
        "kaufpreis": "11 Punkte",
        "miete": "8 Punkte",
        "farbe": "Lila",
        "zusatz_regel": "Ein schneller Verbindungspunkt für starke Besitzserien.",
        "besitzer": None,
    },
    {
        "feld_id": 37,
        "name": "Panoramaexpress",
        "typ": "Bahnhof",
        "kaufpreis": "12 Punkte",
        "miete": "9 Punkte",
        "farbe": "Lila",
        "zusatz_regel": "Perfekt für alle, die das Spielbild gern komplettieren.",
        "besitzer": None,
    },
    {
        "feld_id": 38,
        "name": "Siegerstation",
        "typ": "Straße",
        "kaufpreis": "13 Punkte",
        "miete": "10 Punkte",
        "farbe": "Lila",
        "zusatz_regel": "Kurz vor dem Ziel zeigt sich, wer die Runde dominiert.",
        "besitzer": None,
    },
    {
        "feld_id": 39,
        "name": "Servicebeitrag",
        "typ": "Steuer",
        "kaufpreis": None,
        "miete": "4 Punkte",
        "farbe": "Lila",
        "zusatz_regel": "Ein neutraler Pflichtstopp, bevor die Schlussgerade beginnt.",
        "besitzer": None,
    },
    {
        "feld_id": 40,
        "name": "Finale der Freude",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "zusatz_regel": "Die Schlussrunde gehört allen: ein gemeinsamer Jubelmoment zum Abschluss des Kreises.",
        "besitzer": None,
    },
]
