DEFAULT_FIELDS = [
    {
        "feld_id": 1,
        "name": "Los",
        "typ": "Los",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Dunkelgrau",
        "alkohol_typ": "Wasser",
        "alkohol_menge": "0",
        "zusatz_regel": "Starthilfe: 1 Schluck Bier",
        "besitzer": None,
    },
    {
        "feld_id": 2,
        "name": "Biergasse 1",
        "typ": "Strasse",
        "kaufpreis": "2 Schlucke",
        "miete": "1 Schluck",
        "farbe": "Braun",
        "alkohol_typ": "Bier",
        "alkohol_menge": "1 Schluck",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 3,
        "name": "Inndrinks",
        "typ": "Strasse",
        "kaufpreis": "3 Schlucke",
        "miete": "2 Schlucke",
        "farbe": "Braun",
        "alkohol_typ": "Bier",
        "alkohol_menge": "2 Schlucke",
        "zusatz_regel": "Sie bringen dir ein neues Bier.",
        "besitzer": None,
    },
    {
        "feld_id": 4,
        "name": "HTL Anichstrasse",
        "typ": "Gemeinschaft",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Braun",
        "alkohol_typ": "Bier",
        "alkohol_menge": "0",
        "zusatz_regel": "Der Wuerfel bestimmt die Menge.",
        "besitzer": None,
    },
    {
        "feld_id": 5,
        "name": "Bierpalast",
        "typ": "Strasse",
        "kaufpreis": "5 Schlucke",
        "miete": "3 Schlucke",
        "farbe": "Braun",
        "alkohol_typ": "Bier",
        "alkohol_menge": "3 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 6,
        "name": "Biergarten",
        "typ": "Strasse",
        "kaufpreis": "4 Schlucke",
        "miete": "2 Schlucke",
        "farbe": "Braun",
        "alkohol_typ": "Bier",
        "alkohol_menge": "2 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 7,
        "name": "Weinberg",
        "typ": "Strasse",
        "kaufpreis": "1 Glas",
        "miete": "3 Schlucke",
        "farbe": "Hellblau",
        "alkohol_typ": "Wein",
        "alkohol_menge": "1 Glas",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 8,
        "name": "Sektempfang",
        "typ": "Strasse",
        "kaufpreis": "3 Schlucke",
        "miete": "2 Schlucke",
        "farbe": "Hellblau",
        "alkohol_typ": "Wein",
        "alkohol_menge": "2 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 9,
        "name": "Weinstube",
        "typ": "Strasse",
        "kaufpreis": "4 Glaeser",
        "miete": "3 Glaeser",
        "farbe": "Hellblau",
        "alkohol_typ": "Wein",
        "alkohol_menge": "3 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 10,
        "name": "Alkohol-Joker",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "alkohol_typ": "Joker",
        "alkohol_menge": "0",
        "zusatz_regel": "Waehle einen beliebigen Alkoholtyp.",
        "besitzer": None,
    },
    {
        "feld_id": 11,
        "name": "Longdrink-Meile",
        "typ": "Strasse",
        "kaufpreis": "6 Schlucke",
        "miete": "5 Schlucke",
        "farbe": "Pink",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "5 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 12,
        "name": "Cocktail-Strasse",
        "typ": "Strasse",
        "kaufpreis": "1 Glas",
        "miete": "1 Glas",
        "farbe": "Pink",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "1 Glas",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 13,
        "name": "Gin-Allee",
        "typ": "Strasse",
        "kaufpreis": "5 cl",
        "miete": "2 cl",
        "farbe": "Pink",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "2 cl",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 14,
        "name": "Whiskey-Platz",
        "typ": "Strasse",
        "kaufpreis": "6 cl",
        "miete": "3 cl",
        "farbe": "Pink",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "3 cl",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 15,
        "name": "Sektbar",
        "typ": "Strasse",
        "kaufpreis": "3 Glaeser",
        "miete": "2 Glaeser",
        "farbe": "Pink",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "2 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 16,
        "name": "Vodka-Strasse",
        "typ": "Strasse",
        "kaufpreis": "3 cl",
        "miete": "2 cl",
        "farbe": "Orange",
        "alkohol_typ": "Schnaps",
        "alkohol_menge": "2 cl",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 17,
        "name": "Rum-Meile",
        "typ": "Strasse",
        "kaufpreis": "4 cl",
        "miete": "3 cl",
        "farbe": "Orange",
        "alkohol_typ": "Schnaps",
        "alkohol_menge": "3 cl",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 18,
        "name": "Tequila-Kreuzung",
        "typ": "Strasse",
        "kaufpreis": "2 Shots",
        "miete": "1 Shot",
        "farbe": "Orange",
        "alkohol_typ": "Shot",
        "alkohol_menge": "1 Shot",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 19,
        "name": "Absinth-Allee",
        "typ": "Strasse",
        "kaufpreis": "3 Shots",
        "miete": "2 Shots",
        "farbe": "Orange",
        "alkohol_typ": "Shot",
        "alkohol_menge": "2 Shots",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 20,
        "name": "Hydrations-Station",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "alkohol_typ": "Wasser",
        "alkohol_menge": "0",
        "zusatz_regel": "Trinke Wasser und ueberspringe den naechsten Shot.",
        "besitzer": None,
    },
    {
        "feld_id": 21,
        "name": "Bozner-Platz",
        "typ": "Strasse",
        "kaufpreis": "4 Schlucke",
        "miete": "3 Schlucke",
        "farbe": "Rot",
        "alkohol_typ": "Wein",
        "alkohol_menge": "3 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 22,
        "name": "Rotwein-Gasse",
        "typ": "Strasse",
        "kaufpreis": "5 Glaeser",
        "miete": "4 Glaeser",
        "farbe": "Rot",
        "alkohol_typ": "Wein",
        "alkohol_menge": "4 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 23,
        "name": "Gefaengnis",
        "typ": "Gefaengnis",
        "kaufpreis": None,
        "miete": "3 Shots",
        "farbe": "Rot",
        "alkohol_typ": "Shot",
        "alkohol_menge": "3 Shots",
        "zusatz_regel": "Nachzahlung oder eine Runde Pause.",
        "besitzer": None,
    },
    {
        "feld_id": 24,
        "name": "Weinhandlung",
        "typ": "Strasse",
        "kaufpreis": "6 Glaeser",
        "miete": "5 Glaeser",
        "farbe": "Rot",
        "alkohol_typ": "Wein",
        "alkohol_menge": "5 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 25,
        "name": "Sektkellerei",
        "typ": "Strasse",
        "kaufpreis": "7 Glaeser",
        "miete": "6 Glaeser",
        "farbe": "Rot",
        "alkohol_typ": "Wein",
        "alkohol_menge": "6 Glaeser",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 26,
        "name": "Bierstube",
        "typ": "Strasse",
        "kaufpreis": "5 Schlucke",
        "miete": "4 Schlucke",
        "farbe": "Gelb",
        "alkohol_typ": "Bier",
        "alkohol_menge": "4 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 27,
        "name": "Biergarten Gold",
        "typ": "Strasse",
        "kaufpreis": "6 Schlucke",
        "miete": "5 Schlucke",
        "farbe": "Gelb",
        "alkohol_typ": "Bier",
        "alkohol_menge": "5 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 28,
        "name": "Brauerei",
        "typ": "Werk",
        "kaufpreis": "1 Liter Bier",
        "miete": None,
        "farbe": "Gelb",
        "alkohol_typ": "Bier",
        "alkohol_menge": "1 Liter",
        "zusatz_regel": "Katerprophylaxe: 2 Runden Schutz.",
        "besitzer": None,
    },
    {
        "feld_id": 29,
        "name": "Bierfest",
        "typ": "Strasse",
        "kaufpreis": "7 Schlucke",
        "miete": "6 Schlucke",
        "farbe": "Gelb",
        "alkohol_typ": "Bier",
        "alkohol_menge": "6 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 30,
        "name": "Kater-Polizei",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "alkohol_typ": "Wasser",
        "alkohol_menge": "0",
        "zusatz_regel": "Wenn du betrunken bist: 1 Runde Pause.",
        "besitzer": None,
    },
    {
        "feld_id": 31,
        "name": "Tiki-Bar",
        "typ": "Strasse",
        "kaufpreis": "8 Schlucke",
        "miete": "7 Schlucke",
        "farbe": "Gruen",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "7 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 32,
        "name": "Mojito-Meile",
        "typ": "Strasse",
        "kaufpreis": "9 Schlucke",
        "miete": "8 Schlucke",
        "farbe": "Gruen",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "8 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 33,
        "name": "Daiquiri-Diele",
        "typ": "Strasse",
        "kaufpreis": "10 Schlucke",
        "miete": "9 Schlucke",
        "farbe": "Gruen",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "9 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 34,
        "name": "Caipirinha-Club",
        "typ": "Strasse",
        "kaufpreis": "11 Schlucke",
        "miete": "10 Schlucke",
        "farbe": "Gruen",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "10 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 35,
        "name": "Pina-Colada-Paradies",
        "typ": "Strasse",
        "kaufpreis": "12 Schlucke",
        "miete": "11 Schlucke",
        "farbe": "Gruen",
        "alkohol_typ": "Mixgetraenk",
        "alkohol_menge": "11 Schlucke",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 36,
        "name": "Vodka-Bahnhof",
        "typ": "Bahnhof",
        "kaufpreis": "6 cl",
        "miete": "3 Shots",
        "farbe": "Lila",
        "alkohol_typ": "Shot",
        "alkohol_menge": "3 Shots",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 37,
        "name": "Sake-Bahnhof",
        "typ": "Bahnhof",
        "kaufpreis": "5 cl",
        "miete": "2 Shots",
        "farbe": "Lila",
        "alkohol_typ": "Shot",
        "alkohol_menge": "2 Shots",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 38,
        "name": "Jagermeister-Station",
        "typ": "Strasse",
        "kaufpreis": "4 Shots",
        "miete": "3 Shots",
        "farbe": "Lila",
        "alkohol_typ": "Shot",
        "alkohol_menge": "3 Shots",
        "zusatz_regel": None,
        "besitzer": None,
    },
    {
        "feld_id": 39,
        "name": "Steuer",
        "typ": "Steuer",
        "kaufpreis": None,
        "miete": "4 Schlucke",
        "farbe": "Lila",
        "alkohol_typ": "Shot",
        "alkohol_menge": "4 Shots",
        "zusatz_regel": "An alle verteilen.",
        "besitzer": None,
    },
    {
        "feld_id": 40,
        "name": "Endspurt",
        "typ": "Spezial",
        "kaufpreis": None,
        "miete": None,
        "farbe": "Rainbow",
        "alkohol_typ": "Shot",
        "alkohol_menge": "3 Shots",
        "zusatz_regel": "Der letzte Spieler trinkt doppelt.",
        "besitzer": None,
    },
]
